// frontend/student-app/src/pages/Login.jsx
import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { useNavigate } from 'react-router-dom';
import './Login.css';

const Login = () => {
  const [regNo, setRegNo] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const { login } = useAuth();
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      await login(regNo, password);
      navigate('/questions');
    } catch (err) {
      setError(err.response?.data?.message || 'Login failed. Check your credentials.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-page">
      <div className="glass-bg-animated"></div>
      <div className="login-card glass">
        <div className="login-header">
          <div className="login-icon">🎓</div>
          <h1>Student Portal</h1>
          <p>Login with your Register Number</p>
        </div>
        <form onSubmit={handleSubmit} className="login-form">
          <div className="form-group">
            <label htmlFor="regNo">Register Number</label>
            <input
              id="regNo"
              type="text"
              placeholder="e.g. 22CS001"
              value={regNo}
              onChange={(e) => setRegNo(e.target.value)}
              required
            />
          </div>
          <div className="form-group">
            <label htmlFor="password">Password</label>
            <input
              id="password"
              type="password"
              placeholder="Enter your password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </div>
          {error && <div className="error-msg">{error}</div>}
          <button type="submit" className="btn-login" disabled={loading}>
            {loading ? 'Logging in...' : 'Login'}
          </button>
        </form>
        <p className="back-link">
          <a href="http://localhost:5000">← Back to Home</a>
        </p>
      </div>
    </div>
  );
};

export default Login;

// frontend/staff-app/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, FormArray, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthService } from '../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  // Advanced Angular Technique: Reactive Forms
  loginForm: FormGroup;
  error = '';
  loading = false;

  constructor(private fb: FormBuilder, private auth: AuthService, private router: Router) {
    this.loginForm = this.fb.group({
      regNo: ['', [Validators.required]],
      password: ['', [Validators.required, Validators.minLength(4)]]
    });
  }

  onSubmit() {
    if (this.loginForm.invalid) return;
    this.loading = true;
    this.error = '';
    const { regNo, password } = this.loginForm.value;
    this.auth.login(regNo, password).subscribe({
      next: () => this.router.navigate(['/dashboard']),
      error: (err) => {
        this.error = err.error?.message || 'Login failed. Staff only access.';
        this.loading = false;
      }
    });
  }
}

<div class="login-page">
  <div class="glass-bg-anim"></div>
  <div class="login-card">
    <div class="login-header">
      <div class="icon">🏫</div>
      <h1>Staff Portal</h1>
      <p>Login to manage questions &amp; view student results</p>
    </div>

    <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="login-form">
      <div class="form-group">
        <label for="regNo">Staff ID / Register Number</label>
        <input id="regNo" type="text" formControlName="regNo" placeholder="e.g. STAFF001" />
        <span class="field-err" *ngIf="loginForm.get('regNo')?.invalid && loginForm.get('regNo')?.touched">
          Staff ID is required
        </span>
      </div>

      <div class="form-group">
        <label for="password">Password</label>
        <input id="password" type="password" formControlName="password" placeholder="Min 4 characters" />
        <span class="field-err" *ngIf="loginForm.get('password')?.invalid && loginForm.get('password')?.touched">
          Password must be at least 4 characters
        </span>
      </div>

      <div class="error-msg" *ngIf="error">{{ error }}</div>

      <button type="submit" class="btn-login" [disabled]="loading || loginForm.invalid">
        {{ loading ? 'Logging in...' : 'Login as Staff' }}
      </button>
    </form>

    <p class="back-link"><a href="http://localhost:5000">← Back to Home</a></p>
  </div>
</div>
